---
services:
  ansible-role-example-role:
    tty: true
    # Build the container from the Dockerfile before we run it
    build:
      context: .
      dockerfile: ./Dockerfile
    # If you have build and pushed this container to a registry you can use it below and disable build above
    # image: tools-${ARCH}:latest
    network_mode: "bridge"
    volumes:
      # Mounts the project folder into the container
      - ".:/app"
      # Mount your ~/.ssh folder into the container
      - "~/.ssh:/home/ubuntu/.ssh"
      # For GPG Auth to Github
      - "~/.gnupg:/home/ubuntu/.gnupg"
    working_dir: "/app"
    environment:
      - ARCH
      - GPG_TTY=/dev/pts/1
