---

#- name: "Ansible | List all known variables and facts"
#  debug:
#    var: hostvars[inventory_hostname]
#    verbosity: 1

- name: OS
  debug:
    msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }} on {{ ansible_facts['system_vendor'] }}"

- set_fact:
    cloud: "google"
  when:
    ansible_facts['system_vendor'] == 'Google'

- set_fact:
    cloud: "azure"
  when:
    ansible_facts['system_vendor'] == 'Microsoft Corporation'

- set_fact:
    cloud: "amazon"
  when:
    ansible_facts['system_vendor'] == 'Xen'

- set_fact:
    cloud: "vagrant"
  when:
    ansible_facts['system_vendor'] == 'innotek GmbH'

#- name: Write Ansible hostvars to file
#  copy:
#    content: "{{ hostvars[inventory_hostname] }}"
#    dest: /soe-{{ version_number }}.json
#    mode: "0644"

- name: Ensure user ansible is present
  ansible.builtin.user:
    name: ansible
    password: "{{ 'aix1rii3Bahshuleikei5y' | password_hash('sha512') }}"
    update_password: on_create
    comment: Ansible Tower
    uid: 1040
    shell: /bin/bash
    groups: users,sudo
    append: yes
