---

- name: "deb | List all known variables and facts"
  ansible.builtin.debug:
    var: hostvars[inventory_hostname]
    verbosity: 1

- name: 'deb | OS'
  ansible.builtin.debug:
    msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }} on {{ ansible_facts['system_vendor'] }}"
  # tags:
  #   - always

- name: 'deb | VM Name and IP'
  ansible.builtin.debug:
    msg: "vm_name: {{ vm_name }} vm_ip: {{ vm_ip }}"
  # tags:
  #   - always

- name: 'deb | Set cloud fact to google'
  ansible.builtin.set_fact:
    cloud: "google"
  when:
    ansible_facts['system_vendor'] == 'Google'
  # tags:
  #   - always

- name: 'deb | Set cloud fact to azure'
  ansible.builtin.set_fact:
    cloud: "azure"
  when:
    ansible_facts['system_vendor'] == 'Microsoft Corporation'
  # tags:
  #   - always

- name: 'deb | Set cloud fact to amazon'
  ansible.builtin.set_fact:
    cloud: "amazon"
  when:
    ansible_facts['system_vendor'] == 'Xen'
  # tags:
  #   - always

- name: 'deb | Set cloud fact to vagrant'
  ansible.builtin.set_fact:
    cloud: "vagrant"
  when:
    ansible_facts['system_vendor'] == 'innotek GmbH'
  # tags:
  #   - always

- name: 'deb | Update apt repo and cache'
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  # tags:
  #   - day1

- name: 'deb | Upgrade all packages'
  ansible.builtin.apt:
    upgrade: dist
    force_apt_get: yes
  # tags:
  #   - day1

- name: 'deb | Install systemd-timesyncd'
  ansible.builtin.apt:
    name: systemd-timesyncd
    state: present

- name: 'deb | Create file /etc/default/ufw'
  ansible.builtin.file:
    path: /etc/default/ufw
    state: touch

- name: 'deb | Write Ansible hostvars to file'
  ansible.builtin.copy:
    content: "{{ hostvars[inventory_hostname] }}"
    dest: /soe-build-{{ version_number }}.json
    mode: "0644"
  # tags:
  #   - day0

# WARNING!! This is just a POC normally we would not enter a password in clear text
- name: 'deb | Ensure user ansible is present'
  ansible.builtin.user:
    name: ansible
    password: "{{ 'aix1rii3Bahshuleikei5y' | password_hash('sha512') }}"
    # password: "$6$IBULZeGd6UP6Jkg3$QqdevUQs.VDuMnT8prurhLuz3PErfoUHXg0/culpF4uj8RdZJ7UyuOG9LAz2B16Nao1jFe5X.NIKw0eYBKyXO1"
    update_password: on_create
    comment: Ansible Tower
    uid: 1040
    shell: /bin/bash
    groups: users,sudo
    append: yes
  # tags:
  #   - day0
