---

- name: "Ansible Role Example Role List Ansible facts"
  ansible.builtin.debug:
    var: hostvars[inventory_hostname]
    verbosity: 1

- name: 'Ansible Role Example Role Enterprise Linux'
  ansible.builtin.include_tasks: el.yml
  when: >
    (ansible_facts['distribution'] == "RedHat")
    or
    (ansible_facts['distribution'] == "CentOS")

- name: 'Ansible Role Example Role Ubuntu / Debian'
  ansible.builtin.include_tasks: deb.yml
  # when: >
  #   (ansible_facts['distribution'] == "Ubuntu")
  #   or
  #   (ansible_facts['distribution'] == "Debian")

- name: 'Ansible Role Example Role Windows'
  ansible.builtin.include_tasks: windows.yml
  when: >
    (ansible_facts['distribution'] is match("Microsoft Windows.*"))
