---

- include: el.yml
  when: >
    (ansible_facts['distribution'] == "RedHat"
    and ansible_facts['distribution_major_version'] == "8")
    or
    (ansible_facts['distribution'] == "RedHat"
    and ansible_facts['distribution_major_version'] == "7")
    or
    (ansible_facts['distribution'] == "CentOS"
    and ansible_facts['distribution_major_version'] == "8")
    or
    (ansible_facts['distribution'] == "CentOS"
    and ansible_facts['distribution_major_version'] == "7")

- include: deb.yml
  when: >
    (ansible_facts['distribution'] == "Ubuntu"
    and ansible_facts['distribution_major_version'] == "18")
    or
    (ansible_facts['distribution'] == "Ubuntu"
    and ansible_facts['distribution_major_version'] == "20")
    or
    (ansible_facts['distribution'] == "Debian"
    and ansible_facts['distribution_major_version'] == "9")
    or
    (ansible_facts['distribution'] == "Debian"
    and ansible_facts['distribution_major_version'] == "10")

- include: windows.yml
  when: >
    (ansible_facts['distribution_major_version'] == "10"
    and ansible_facts['distribution'] is match("Microsoft Windows Server 2019.*"))
    or
    (ansible_facts['distribution_major_version'] == "10"
    and ansible_facts['distribution'] is match("Microsoft Windows Server 2016.*"))
    or
    (ansible_facts['distribution_major_version'] == "6"
    and ansible_facts['distribution'] is match("Microsoft Windows Server 2012.*"))